name: Release-alpha

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: |
        corepack enable
        pnpm --version
    - run: pnpm install --frozen-lockfile
    - run: pnpm --filter ./packages/model run coverage
    - run: pnpm --filter ./packages/model run build
    - uses: JS-DevTools/npm-publish@v1
      with:
        package: ./packages/model/package.json
        token: ${{ secrets.NPM_TOKEN }}
