name: Manual-test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: |
        corepack enable
        pnpm --version
    - run: pnpm install --frozen-lockfile
    - run: pnpm --filter ./packages/model run type-check
    - run: pnpm --filter ./packages/model run coverage
    - run: pnpm --filter ./packages/model run build
    # - run: pnpm --filter ./packages/model run docs:build
    # - run: pnpm --filter ./packages/docs run build
    - run: pnpm --filter ./packages/mini-app-demo run type-check
    - run: pnpm --filter ./packages/mini-app-demo run build:mp-weixin
